name: embed_video_player
description: A Flutter package for embedding video players from various sources (VK, YouTube, and generic iframes) using WebView.
version: 1.1.0

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.6.0
  dio: ^5.4.1
  flutter_inappwebview: ^6.2.0-beta.2
  flutter_inappwebview_platform_interface: ^1.4.0-beta.2
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
